### PR TITLE
2_Manorama branch files commit

### PR DESCRIPTION
**Pull request by devopstraininghub**
Hi Team , 

Would like to merge 2_Manorama branch into Manorama branch . 

Please review and approve

### CODE REVIEW

**Review by alisid202 — COMMENTED** [review]
hi team looks good plz go ahead

**Review by vinaymatangi — APPROVED** [review]
Hi Team , 

it looks good to me , Please proceed with merge .

**Comment by devopstraininghub** [comment]
Code has been reviewed by team , Merging the code . 
thank you !

**Comment by DevuniDivya** [comment]
Hi team    
                It looks good to me, please proceed to merge. 

thank you..

**Pull request merged**
